version: "3"

services:
  db:
    container_name: talker_manager_db
    image: mysql:8.0.33
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}